import { StyleSheet } from 'react-native';

import { spacing, typography, type ThemeColors } from '../../theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.s18,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s24,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.surfaceStrongAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s12,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
  },
  notificationChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceSecondary,
  },
  notificationGlyph: {
    fontSize: 16,
    fontWeight: typography.weight.bold,
    color: colors.textSecondary,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentBlue,
  },
  avatarText: {
    color: colors.textInverse,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.bold,
  },
  summaryGrid: {
    gap: spacing.s14,
    marginBottom: spacing.s20,
  },
  summaryTile: {
    borderRadius: 26,
    paddingHorizontal: spacing.s18,
    paddingVertical: spacing.s18,
    overflow: 'hidden',
    minHeight: 176,
  },
  summaryTilePrimary: {
    backgroundColor: colors.surfaceStrongAlt,
  },
  summaryTileSecondary: {
    backgroundColor: colors.investmentHighlight,
  },
  summaryTileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s16,
  },
  summaryTileEyebrow: {
    fontSize: typography.size.sm,
    color: colors.textInverseMuted,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    fontWeight: typography.weight.semiBold,
  },
  summaryTileEyebrowSecondary: {
    color: '#1C8E49',
  },
  summaryBadge: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: spacing.s10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryBadgeLight: {
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  summaryBadgeDark: {
    backgroundColor: 'rgba(10, 138, 56, 0.1)',
  },
  summaryBadgeText: {
    fontSize: typography.size.xs,
    fontWeight: typography.weight.semiBold,
    color: colors.textInverse,
  },
  summaryBadgeTextDark: {
    fontSize: typography.size.xs,
    fontWeight: typography.weight.semiBold,
    color: '#1C8E49',
  },
  summaryTileTitle: {
    fontSize: typography.size.md,
    color: colors.textInverse,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s8,
    maxWidth: '72%',
  },
  summaryTileTitleSecondary: {
    color: colors.textPrimary,
  },
  summaryTileAmount: {
    fontSize: 34,
    lineHeight: 38,
    color: colors.textInverse,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s10,
  },
  summaryTileAmountPositive: {
    color: colors.success,
  },
  summaryTileAmountSecondary: {
    color: '#0F8A3F',
  },
  summaryTileCaption: {
    fontSize: typography.size.sm,
    lineHeight: 21,
    color: colors.textInverseMuted,
    maxWidth: '70%',
  },
  summaryTileCaptionSecondary: {
    color: colors.textSecondary,
  },
  summaryTileIconWrap: {
    position: 'absolute',
    right: spacing.s18,
    bottom: spacing.s18,
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryTileIconWrapDark: {
    backgroundColor: 'rgba(10, 138, 56, 0.1)',
  },
  summaryTileIcon: {
    fontSize: 24,
    color: colors.textInverse,
  },
  summaryTileIconSecondary: {
    color: '#1C8E49',
  },
  investGraphicOrbit: {
    position: 'absolute',
    right: -26,
    bottom: -28,
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 10,
    borderColor: 'rgba(10, 122, 56, 0.1)',
  },
  investGraphicCore: {
    position: 'absolute',
    right: 26,
    bottom: 20,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(10, 122, 56, 0.14)',
  },
  investGraphicDot: {
    position: 'absolute',
    right: 72,
    top: 24,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(10, 122, 56, 0.14)',
  },
  investGraphicDotAlt: {
    position: 'absolute',
    right: 88,
    top: 36,
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: 'rgba(10, 122, 56, 0.11)',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.s10,
    marginBottom: spacing.s16,
  },
  sectionHeaderAlt: {
    marginTop: spacing.s28,
    marginBottom: spacing.s16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
  },
  viewAllText: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.semiBold,
    color: colors.primary,
  },
  transactionList: {
    gap: spacing.s16,
  },
  fullScreenLoader: {
    paddingVertical: spacing.xl,
    alignItems: 'center',
  },
  emptyRecent: {
    fontSize: typography.size.sm,
    color: colors.muted,
  },
  insightHero: {
    overflow: 'hidden',
    backgroundColor: colors.surfaceStrong,
    borderRadius: 24,
    padding: spacing.s20,
    marginBottom: spacing.s18,
  },
  insightBadge: {
    alignSelf: 'flex-start',
    color: colors.successBright,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    marginBottom: spacing.s16,
  },
  insightHeadline: {
    color: colors.textInverse,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s12,
    maxWidth: '80%',
  },
  insightBody: {
    color: colors.textInverseMuted,
    fontSize: typography.size.md,
    lineHeight: 26,
    marginBottom: spacing.s18,
    maxWidth: '84%',
  },
  insightButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    paddingHorizontal: spacing.s24,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightButtonText: {
    color: colors.primaryContrast,
    fontSize: typography.size.md,
    fontWeight: typography.weight.semiBold,
  },
  insightDecorationOuter: {
    position: 'absolute',
    right: -48,
    bottom: -42,
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 24,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  insightDecorationInner: {
    position: 'absolute',
    right: 34,
    bottom: 18,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  noteCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 24,
    padding: spacing.s20,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  noteIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s14,
  },
  noteIcon: {
    color: colors.textSecondary,
    fontSize: typography.size.md,
    fontWeight: typography.weight.bold,
  },
  noteContent: {
    flex: 1,
  },
  noteTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s8,
  },
  noteBody: {
    color: colors.muted,
    fontSize: typography.size.md,
    lineHeight: 25,
  },
});
