import { StyleSheet } from 'react-native';

import { spacing, typography, type ThemeColors } from '../../theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.s18,
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  headerTitle: {
    fontSize: typography.size.lg,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
    marginBottom: spacing.s24,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 24,
    padding: spacing.s6,
    marginBottom: spacing.s24,
  },
  segment: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  segmentActive: {
    backgroundColor: colors.surfaceStrong,
  },
  segmentText: {
    fontSize: typography.size.md,
    color: colors.muted,
    fontWeight: typography.weight.semiBold,
  },
  segmentTextActive: {
    color: colors.textInverse,
  },
  heroCard: {
    borderRadius: 28,
    paddingHorizontal: spacing.s24,
    paddingVertical: spacing.s20,
    backgroundColor: colors.surfaceStrongAlt,
    marginBottom: spacing.s24,
  },
  heroLabel: {
    fontSize: typography.size.sm,
    color: colors.textInverseMuted,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s12,
  },
  heroAmount: {
    fontSize: typography.size.xl,
    lineHeight: 34,
    color: colors.textInverse,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s16,
  },
  heroDeltaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroDeltaPill: {
    borderRadius: 18,
    backgroundColor: colors.successMuted,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s8,
    marginRight: spacing.s12,
  },
  heroDeltaText: {
    color: colors.successBright,
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
  },
  heroDeltaCaption: {
    color: colors.textInverseMuted,
    fontSize: typography.size.sm,
  },
  analysisCard: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 24,
    padding: spacing.s18,
    marginBottom: spacing.s24,
  },
  analysisHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.s12,
  },
  analysisTitle: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
    marginBottom: spacing.s4,
  },
  analysisSubtitle: {
    fontSize: typography.size.sm,
    color: colors.muted,
  },
  analysisAccentWrap: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.s4,
    paddingTop: spacing.s4,
  },
  analysisAccentShort: {
    width: 4,
    height: 20,
    borderRadius: 999,
    backgroundColor: colors.successSoft,
  },
  analysisAccentMid: {
    width: 4,
    height: 28,
    borderRadius: 999,
    backgroundColor: colors.success,
  },
  analysisAccentTall: {
    width: 4,
    height: 48,
    borderRadius: 999,
    backgroundColor: colors.successBright,
  },
  chartCanvas: {
    position: 'relative',
    paddingTop: spacing.s40,
  },
  chartArea: {
    height: 210,
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: spacing.s10,
    paddingBottom: spacing.s8,
  },
  chartScrollContent: {
    paddingRight: spacing.s10,
  },
  chartColumn: {
    width: 52,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginRight: spacing.s8,
  },
  chartBar: {
    width: 40,
    borderRadius: 12,
    backgroundColor: colors.chartBar,
    marginBottom: spacing.s12,
  },
  chartBarFilled: {
    backgroundColor: colors.chartBarFilled,
  },
  chartBarSelected: {
    borderWidth: 2,
    borderColor: colors.surfaceStrong,
    backgroundColor: colors.surfaceStrong,
  },
  chartLabel: {
    fontSize: typography.size.sm,
    color: colors.muted,
    fontWeight: typography.weight.semiBold,
  },
  chartLabelSelected: {
    color: colors.textPrimary,
  },
  chartTooltipBubble: {
    position: 'absolute',
    top: 0,
    borderRadius: 16,
    backgroundColor: colors.surfaceStrong,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s10,
  },
  chartTooltipBubbleAmount: {
    fontSize: typography.size.sm,
    color: colors.textInverse,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s4,
  },
  chartTooltipBubbleDate: {
    fontSize: typography.size.xs,
    color: colors.textInverseMuted,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s16,
  },
  sectionHeaderLoose: {
    marginTop: spacing.s8,
    marginBottom: spacing.s16,
  },
  sectionTitle: {
    fontSize: typography.size.lg,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
  },
  sectionLink: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.semiBold,
    color: colors.primary,
  },
  categoryEmpty: {
    fontSize: typography.size.sm,
    color: colors.muted,
    marginBottom: spacing.s20,
  },
  categoryCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.s14,
  },
  categoryIconBox: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.backgroundSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s14,
  },
  categoryEmoji: {
    fontSize: 22,
  },
  categoryMain: {
    flex: 1,
    paddingRight: spacing.s12,
  },
  categoryTitle: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s4,
  },
  categoryMeta: {
    fontSize: typography.size.sm,
    color: colors.muted,
  },
  categoryRight: {
    width: 92,
    alignItems: 'flex-end',
  },
  categoryAmount: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s10,
  },
  progressTrack: {
    width: 92,
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.progressTrack,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.successBright,
  },
  investmentGrid: {
    flexDirection: 'row',
    gap: spacing.s16,
  },
  investmentCard: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    borderRadius: 24,
    paddingHorizontal: spacing.s20,
    paddingVertical: spacing.s20,
    minHeight: 188,
  },
  lockBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.s6,
    borderRadius: 999,
    backgroundColor: colors.surfaceStrong,
    marginBottom: spacing.s16,
  },
  lockBadgeText: {
    color: colors.textInverse,
    fontSize: typography.size.xs,
    fontWeight: typography.weight.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  investmentIconDark: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceStrong,
    marginBottom: spacing.s24,
  },
  investmentIconGreen: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    marginBottom: spacing.s24,
  },
  investmentIconText: {
    fontSize: typography.size.lg,
  },
  investmentLabel: {
    fontSize: typography.size.sm,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    color: colors.muted,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s12,
  },
  investmentValue: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s12,
  },
  investmentNote: {
    fontSize: typography.size.sm,
    color: colors.primary,
    fontWeight: typography.weight.semiBold,
  },
  lockedHint: {
    marginTop: spacing.s12,
    fontSize: typography.size.sm,
    lineHeight: 20,
    color: colors.muted,
  },
  loaderCard: {
    minHeight: 240,
    borderRadius: 28,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    borderRadius: 28,
    backgroundColor: colors.surface,
    padding: spacing.s24,
  },
  emptyTitle: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
    marginBottom: spacing.s8,
  },
  emptyMessage: {
    fontSize: typography.size.sm,
    color: colors.muted,
    lineHeight: 22,
  },
  breakdownScreen: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.s18,
  },
  breakdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.s20,
  },
  breakdownBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s12,
  },
  breakdownBackIcon: {
    fontSize: 20,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
    marginTop: -2,
  },
  breakdownTitle: {
    fontSize: typography.size.lg,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
  },
  breakdownList: {
    paddingBottom: spacing.s12,
  },
  breakdownGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  breakdownTile: {
    width: '48%',
    aspectRatio: 1,
    backgroundColor: colors.surface,
    borderRadius: 20,
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s16,
    marginBottom: spacing.s16,
  },
  breakdownTileIconBox: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.backgroundSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.s16,
  },
  breakdownTileTitle: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s6,
  },
  breakdownTileMeta: {
    fontSize: typography.size.sm,
    color: colors.muted,
    marginBottom: spacing.s12,
  },
  breakdownTileAmount: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
    fontWeight: typography.weight.bold,
    marginBottom: spacing.s10,
  },
});
