import type { Category } from '../types/categories';

export const categorySeeds: Category[] = [
  {
    id: 'food',
    type: 'expense',
    name: 'Food',
    emoji: '🍔',
    isDefault: true,
    labelKey: 'categories.expense.food',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'transport',
    type: 'expense',
    name: 'Transport',
    emoji: '🚗',
    isDefault: true,
    labelKey: 'categories.expense.transport',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'shopping',
    type: 'expense',
    name: 'Shopping',
    emoji: '🛍️',
    isDefault: true,
    labelKey: 'categories.expense.shopping',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'entertainment',
    type: 'expense',
    name: 'Entertainment',
    emoji: '🎬',
    isDefault: true,
    labelKey: 'categories.expense.entertainment',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'bills',
    type: 'expense',
    name: 'Bills',
    emoji: '💡',
    isDefault: true,
    labelKey: 'categories.expense.bills',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'health',
    type: 'expense',
    name: 'Health',
    emoji: '🩺',
    isDefault: true,
    labelKey: 'categories.expense.health',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'other',
    type: 'expense',
    name: 'Other',
    emoji: '📦',
    isDefault: true,
    labelKey: 'categories.expense.other',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'salary',
    type: 'income',
    name: 'Salary',
    emoji: '💼',
    isDefault: true,
    labelKey: 'categories.income.salary',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'freelance',
    type: 'income',
    name: 'Freelance',
    emoji: '🧑‍💻',
    isDefault: true,
    labelKey: 'categories.income.freelance',
    createdAt: new Date(0).toISOString(),
  },
  {
    id: 'other_income',
    type: 'income',
    name: 'Other',
    emoji: '✨',
    isDefault: true,
    labelKey: 'categories.income.other',
    createdAt: new Date(0).toISOString(),
  },
];
