export const strings = {
  navigation: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    analysis: 'Analysis',
    settings: 'Settings',
    addAccessibility: 'Add',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Manage your preferences here.',
    profileBadge: 'Pro Account',
    helpCenterSubject: 'Monetra help center request',
    helpCenterBody:
      'Hello Monetra support,\n\nI need help with my account and app usage.\n\nThanks.',
    helpFallbackMessage:
      'Unable to open your mail app. Please contact xpense.help@gmail.com directly.',
    accountPreferencesTitle: 'Account Preferences',
    accountPreferencesDescription: 'These options will be expanded in a future update.',
    primaryCurrencyLabel: 'Primary Currency',
    primaryCurrencyValue: 'Indian Rupee (₹)',
    primaryCurrencyDescription: 'Currency selection will be handled in a future update.',
    languageLabel: 'Language',
    languageValue: 'English (India)',
    languageDescription: 'Language settings will be handled in a future update.',
    appearanceTitle: 'Appearance',
    themeLabel: 'Dark Mode',
    themeDescription: 'Switch between light and dark appearance.',
    themeLight: 'Light',
    themeDark: 'Dark',
    manageCategoriesLabel: 'Manage Categories',
    manageCategoriesDescription: 'Organize your expense and income categories.',
    manageCategoriesScreenTitle: 'Manage Categories',
    manageCategoriesListTitle: 'Your Categories',
    manageCategoriesAddTitle: 'Add Category',
    manageCategoriesEditTitle: 'Edit Category',
    manageCategoriesAddButton: 'Add Category',
    manageCategoriesSaveChanges: 'Save Changes',
    manageCategoriesCancelEdit: 'Cancel',
    manageCategoriesEmptyTitle: 'No categories yet',
    manageCategoriesEmptyMessage: 'Add your first category to start organizing entries.',
    manageCategoriesUnusedMeta: 'Not used in any transactions',
    manageCategoriesUsedMeta: 'Used in {count} transactions',
    manageCategoriesEditAction: 'Edit',
    manageCategoriesDeleteAction: 'Delete',
    manageCategoriesDeleteTitle: 'Delete category?',
    manageCategoriesDeleteMessage:
      'Delete "{category}"? Existing transactions will keep their saved category snapshot.',
    manageCategoriesDeleteCancel: 'Cancel',
    manageCategoriesDeleteConfirm: 'Delete',
    manageCategoriesNameError: 'Please enter a category name.',
    securityTitle: 'Security & Privacy',
    securityDescription: 'Password tools are coming later. Biometric can be toggled now.',
    passwordSecurityLabel: 'Password & Security',
    passwordSecurityValue: 'Coming Soon',
    passwordSecurityDescription: 'Password management will be handled in a future update.',
    biometricLabel: 'Biometric Authentication',
    biometricDescription: 'Biometric login will be available in a future update.',
    biometricOff: 'Off',
    biometricOn: 'On',
    supportTitle: 'Support & Info',
    supportDescription: 'Help, about details, and your logout action.',
    helpCenterLabel: 'Help Center',
    helpCenterDescription: 'Documentation & support by email',
    aboutLabel: 'About Monetra',
    aboutDescriptionPrefix: 'Version',
    logoutAction: 'Log out',
    loggingOutValue: 'Working...',
    currentSelectionNone: 'Not set',
  },
  auth: {
    title: 'Welcome Back',
    subtitle: 'Manage your financial ledger with precision and ease.',
    userIdPlaceholder: 'User ID',
    passwordPlaceholder: 'Password',
    loginButton: 'Sign In to Dashboard',
    loginFailed: 'Unable to sign in right now.',
    forgotPassword: 'Forgot password?',
    createAccountPrompt: 'Don’t have an account?',
    createAccountAction: 'Create account',
    adminEmail: 'xpense.help@gmail.com',
    forgotPasswordSubject: 'Monetra password help request',
    forgotPasswordBody:
      'Hello Monetra admin,\n\nI need help resetting my Monetra password for user ID:\n\nThanks.',
    createAccountSubject: 'Monetra account creation request',
    createAccountBody:
      'Hello Monetra admin,\n\nI would like a Monetra account created for me. My details are:\n\nThanks.',
    emailFallbackMessage:
      'Unable to open your mail app. Please contact xpense.help@gmail.com directly.',
  },
  transactionsScreen: {
    title: 'Transactions',
    subtitle: 'All expenses and income in one place.',
    searchPlaceholder: 'Search by date, description, category, or type',
    monthSearchPlaceholder: 'Search this month',
    emptyTitle: 'No transactions yet',
    emptyMessage: 'Add your first expense or income to see it here.',
    emptySearchTitle: 'No matching transactions',
    emptySearchMessage: 'Try a different search term.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    uncategorized: 'Uncategorized',
    monthTotalLabel: 'Total spent',
    monthDetailBreakdown: 'Category Breakdown',
    monthDetailCategoryTransactions: 'Transactions',
    monthDetailRecent: 'Month Activity',
  },
  dashboardScreen: {
    title: 'Dashboard',
    subtitle: 'Your money at a glance.',
    spendingTitle: 'This month spending',
    spendingTrend: 'Live from your expense activity',
    investmentTitle: 'This month investment',
    investmentAmount: '0',
    investmentTrend: 'Investment module coming in a future update',
    recentTitle: 'Latest Transactions',
    viewAll: 'View All',
    emptyRecent: 'No transactions yet.',
    insightTitle: 'Investment Insights',
    insightBadge: 'Expert Recommendation',
    insightHeadline: 'Build your investment layer next',
    insightBody:
      'Your expense and income data are syncing well. Investment tracking can plug into this dashboard once we add the module.',
    insightAction: 'Plan Investment Flow',
    noteTitle: 'Sync Health',
    noteBody:
      'Your dashboard is showing local-first data with Supabase sync in the background.',
    untitledTransaction: 'Untitled entry',
    todayUpper: 'TODAY',
    yesterdayUpper: 'YESTERDAY',
    daysAgoSuffix: 'DAYS AGO',
  },
  analysisScreen: {
    title: 'Monetra',
    month: 'Month',
    year: 'Year',
    totalSpent: 'Total Spent',
    vsLastMonth: 'vs last month',
    vsLastYear: 'vs last year',
    analysisTitle: 'Analysis',
    analysisSubtitle: 'Expense activity',
    categoriesTitle: 'Categories',
    viewAll: 'View All',
    allCategoriesTitle: 'All Categories',
    categoriesEmpty: 'No category data yet.',
    investmentsTitle: 'Investments',
    investmentsLocked: 'Locked',
    investmentsLockedNote: 'Investment analytics will unlock once the module is built.',
    investmentGrowthTitle: 'PF Growth',
    investmentFundsTitle: 'Mutual Funds',
    chartPeakLabel: 'Peak',
    chartSelectedAmountLabel: 'Expense',
    chartSelectedDateLabel: 'Date',
    noDateSelected: 'Select a bar to inspect',
    noAnalyticsTitle: 'No analytics yet',
    noAnalyticsMessage: 'Add transactions to unlock monthly and yearly insights.',
    failedTitle: 'Unable to load analytics',
    failedMessage: 'Please try again in a moment.',
  },
  popup: {
    transactionAddedTitle: 'Transaction Added',
    transactionAddedMessage: 'Your transaction has been saved locally.',
    okButton: 'OK',
    databaseClearedTitle: 'Local Data Cleared',
    databaseClearedMessage: 'The local database has been reset.',
    transactionFailedTitle: 'Save Failed',
    transactionFailedMessage: 'Something went wrong while saving.',
    comingSoonTitle: 'Coming Soon',
    manageCategoriesMessage:
      'Category management will be available in a future update.',
    languageMessage: 'Language selection will be available in a future update.',
    exportDataMessage: 'Exporting data will be available in a future update.',
    importDataMessage: 'Importing data will be available in a future update.',
    backupSyncMessage: 'Backup and sync will be available in a future update.',
    quickDateMessage:
      'Quick date presets will be available in a future update.',
    recurringMessage:
      'Recurring transactions will be available in a future update.',
    multiCurrencyMessage:
      'Multi-currency support will be available in a future update.',
    investmentFlowMessage:
      'Investment and withdraw flows will be added later in the project.',
  },
  transactions: {
    title: 'Add Transaction',
    expense: 'Expense',
    income: 'Income',
    expenseContext: 'Expense entry',
    incomeContext: 'Income entry',
    expenseContextHint: 'Quick add is set to expense by default.',
    incomeContextHint: 'Capture money received with the same flow.',
    amountLabel: 'Amount',
    amountPlaceholder: '0.00',
    descriptionLabel: 'Description',
    expensePlaceholder: 'What did you buy?',
    incomePlaceholder: 'Source of income',
    amountError: 'Enter a valid amount.',
    descriptionError: 'Description is required.',
    categoryError: 'Please select a category.',
    dateLabel: 'Date',
    categoryLabel: 'Category',
    allCategoriesTitle: 'Choose category',
    addCategoryTitle: 'Add category',
    categoryNameLabel: 'Category name',
    categoryNamePlaceholder: 'Enter category name',
    categoryEmojiLabel: 'Emoji',
    categoryEmojiPlaceholder: '✨',
    addCategoryButton: 'Add and use',
    moreCategories: 'More',
    addExpense: 'Add Expense',
    addIncome: 'Add Income',
    currencySymbol: '₹',
    dateIcon: '📅',
    closeIcon: '×',
    dateLocale: 'en-IN',
    quickActionTitle: 'Choose transaction type',
    quickActionExpense: 'Add expense',
    quickActionIncome: 'Add income',
    quickActionInvestment: 'Add investment',
    quickActionWithdraw: 'Withdraw',
    quickActionCancel: 'Cancel',
  },
  categories: {
    expense: {
      food: 'Food',
      transport: 'Transport',
      shopping: 'Shopping',
      entertainment: 'Entertainment',
      bills: 'Bills',
      health: 'Health',
      other: 'Other',
    },
    income: {
      salary: 'Salary',
      freelance: 'Freelance',
      other: 'Other',
    },
  },
};
