export const strings = {
  navigation: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    analysis: 'Analysis',
    settings: 'Settings',
    addAccessibility: 'Add',
  },
  settings: {
    title: 'Settings',
    subtitle: 'Manage your preferences here.',
    profileBadge: 'Pro Account',
    helpCenterSubject: 'Monetra help center request',
    helpCenterBody:
      'Hello Monetra support,\n\nI need help with my account and app usage.\n\nThanks.',
    helpFallbackMessage:
      'Unable to open your mail app. Please contact xpense.help@gmail.com directly.',
    accountPreferencesTitle: 'Account Preferences',
    accountPreferencesDescription: 'These options will be expanded in a future update.',
    profileLabel: 'Personal Information',
    profileDescription: 'Update your name, email, and phone number.',
    profileScreenTitle: 'Personal Information',
    profileMemberSincePrefix: 'Vault Member Since',
    profileFullNameLabel: 'Full Name',
    profileFullNamePlaceholder: 'Enter your full name',
    profileEmailLabel: 'Email Address',
    profileEmailPlaceholder: 'Enter your email address',
    profilePhoneLabel: 'Phone Number',
    profilePhonePlaceholder: 'Enter your phone number',
    profileVerificationTitle: 'Identity Verification',
    profileVerificationDescription:
      'Your data is encrypted with 256-bit AES protection. Changes to sensitive information may require biometric re-authentication.',
    profileSaveAction: 'Save Changes',
    profileUpdatedMessage: 'Profile updated successfully.',
    profileUpdateFailedMessage: 'Unable to update profile right now. Please try again.',
    profileNameRequiredError: 'Please enter your full name.',
    profileEmailInvalidError: 'Please enter a valid email address.',
    profilePhoneInvalidError: 'Please enter a valid phone number.',
    primaryCurrencyLabel: 'Primary Currency',
    primaryCurrencyDescription: 'Choose the default currency for all amount displays.',
    primaryCurrencyChangeTitle: 'Change currency?',
    primaryCurrencyChangeMessage:
      'All amounts will be shown in {currency}. Existing records are not converted.',
    primaryCurrencyChangeCancel: 'Cancel',
    primaryCurrencyChangeConfirm: 'Change',
    languageLabel: 'Language',
    languageValue: 'English (India)',
    languageDescription: 'Language settings will be handled in a future update.',
    appearanceTitle: 'Appearance',
    themeLabel: 'Dark Mode',
    themeDescription: 'Switch between light and dark appearance.',
    themeLight: 'Light',
    themeDark: 'Dark',
    manageCategoriesLabel: 'Manage Categories',
    manageCategoriesDescription: 'Organize your expense and income categories.',
    manageCategoriesScreenTitle: 'Manage Categories',
    manageCategoriesListTitle: 'Your Categories',
    manageCategoriesAddTitle: 'Add Category',
    manageCategoriesEditTitle: 'Edit Category',
    manageCategoriesAddButton: 'Add Category',
    manageCategoriesSaveChanges: 'Save Changes',
    manageCategoriesCancelEdit: 'Cancel',
    manageCategoriesEmptyTitle: 'No categories yet',
    manageCategoriesEmptyMessage: 'Add your first category to start organizing entries.',
    manageCategoriesUnusedMeta: 'Not used in any transactions',
    manageCategoriesUsedMeta: 'Used in {count} transactions',
    manageCategoriesEditAction: 'Edit',
    manageCategoriesDeleteAction: 'Delete',
    manageCategoriesDeleteTitle: 'Delete category?',
    manageCategoriesDeleteMessage:
      'Delete "{category}"? Existing transactions will keep their saved category snapshot.',
    manageCategoriesDeleteCancel: 'Cancel',
    manageCategoriesDeleteConfirm: 'Delete',
    manageCategoriesNameError: 'Please enter a category name.',
    securityTitle: 'Security & Privacy',
    securityDescription: 'Manage app passcode and account password.',
    passwordSecurityLabel: 'Password & Security',
    passwordSecurityValue: 'Manage',
    passwordSecurityDescription: 'Set app passcode and change login password.',
    passwordSecurityScreenTitle: 'Password & Security',
    appPasscodeSectionTitle: 'App Passcode',
    appPasscodeSectionDescription:
      'Require a 4-digit passcode when opening the app after it is backgrounded.',
    appPasscodeToggleLabel: 'Enable App Passcode',
    appPasscodeStatusOn: 'Enabled',
    appPasscodeStatusOff: 'Disabled',
    appPasscodeCurrentLabel: 'Current Passcode',
    appPasscodeCurrentPlaceholder: 'Enter current 4-digit passcode',
    appPasscodeNewLabel: 'New Passcode',
    appPasscodeNewPlaceholder: 'Enter new 4-digit passcode',
    appPasscodeConfirmLabel: 'Confirm Passcode',
    appPasscodeConfirmPlaceholder: 'Re-enter new passcode',
    appPasscodeSetAction: 'Set Passcode',
    appPasscodeUpdateAction: 'Update Passcode',
    appPasscodeDisableAction: 'Disable Passcode',
    appPasscodeInvalidError: 'Passcode must be exactly 4 digits.',
    appPasscodeMismatchError: 'Passcode and confirmation do not match.',
    appPasscodeCurrentIncorrectError: 'Current passcode is incorrect.',
    appPasscodeDisableConfirmTitle: 'Disable app passcode?',
    appPasscodeDisableConfirmMessage: 'App lock will be turned off on this device.',
    appPasscodeDisableConfirmAction: 'Disable',
    appPasscodeDisableCancelAction: 'Cancel',
    appPasscodeDisableVerificationTitle: 'Confirm App Passcode',
    appPasscodeDisableVerificationSubtitle:
      'Enter your current 4-digit passcode to disable app lock.',
    appPasscodeUpdatedMessage: 'App passcode saved successfully.',
    appPasscodeOpenSetupAction: 'Create New PIN',
    appPasscodeOpenUpdateAction: 'Change PIN',
    appPasscodePinProgressVerify: 'Verify',
    appPasscodePinProgressCreate: 'Create',
    appPasscodePinProgressConfirm: 'Confirm',
    appPasscodePinVerifyTitle: 'Verify Current PIN',
    appPasscodePinVerifySubtitle:
      'Enter your current 4-digit PIN before creating a new one.',
    appPasscodePinCreateTitle: 'Create New PIN',
    appPasscodePinCreateSubtitle:
      'Enter a 4-digit security code to protect your assets and sensitive operations.',
    appPasscodePinConfirmTitle: 'Confirm New PIN',
    appPasscodePinConfirmSubtitle: 'Re-enter your new PIN to finish setup.',
    appPasscodeSecurityCardTitle: 'End-to-End Encryption',
    appPasscodeSecurityCardSubtitle: 'Your PIN is never stored in plain text.',
    accountPasswordSectionTitle: 'Account Login Password',
    accountPasswordSectionDescription:
      'Change the password used for your Monetra account login.',
    accountPasswordCurrentLabel: 'Current Password',
    accountPasswordCurrentPlaceholder: 'Enter current password',
    accountPasswordNewLabel: 'New Password',
    accountPasswordNewPlaceholder: 'Enter new account password',
    accountPasswordConfirmLabel: 'Confirm New Password',
    accountPasswordConfirmPlaceholder: 'Re-enter new account password',
    accountPasswordUpdateAction: 'Change Password',
    accountPasswordUpdatedMessage: 'Account password updated successfully.',
    accountPasswordMinLengthError: 'Password must be at least 8 characters.',
    accountPasswordMismatchError: 'Password and confirmation do not match.',
    accountPasswordCurrentRequiredError: 'Current password is required.',
    accountPasswordCurrentIncorrectError: 'Current password is incorrect.',
    accountPasswordModalTitle: 'Update Password',
    accountPasswordModalSubtitle:
      'Ensure your account remains secure. Use a strong, unique combination of characters.',
    accountPasswordStrengthLabel: 'Password Strength',
    accountPasswordStrengthWeak: 'Weak',
    accountPasswordStrengthMedium: 'Medium',
    accountPasswordStrengthStrong: 'Strong',
    accountPasswordHintMinTitle: 'Min. 8 Characters',
    accountPasswordHintMinDescription:
      'Include a mix of letters, numbers, and symbols.',
    accountPasswordHintUniqueTitle: 'Unique to Vault',
    accountPasswordHintUniqueDescription:
      'Do not reuse passwords from other platforms.',
    accountPasswordLastChangedLabel: 'Last changed recently',
    accountPasswordOpenModalAction: 'Update Password',
    passwordSecurityFailedMessage:
      'Unable to update security settings right now. Please try again.',
    appLockTitle: 'Enter App Passcode',
    appLockSubtitle: 'Unlock Monetra to continue.',
    appLockInputLabel: 'Passcode',
    appLockInputPlaceholder: '4-digit code',
    appLockUnlockAction: 'Unlock',
    appLockInvalidError: 'Incorrect passcode. Try again.',
    biometricLabel: 'Biometric Authentication',
    biometricDescription: 'Biometric login will be available in a future update.',
    biometricOff: 'Off',
    biometricOn: 'On',
    supportTitle: 'Support & Info',
    supportDescription: 'Help, about details, and your logout action.',
    helpCenterLabel: 'Help Center',
    helpCenterDescription: 'Documentation & support by email',
    aboutLabel: 'About Monetra',
    aboutDescriptionPrefix: 'Version',
    logoutAction: 'Log out',
    loggingOutValue: 'Working...',
    currentSelectionNone: 'Not set',
  },
  auth: {
    title: 'Welcome Back',
    subtitle: 'Manage your financial ledger with precision and ease.',
    userIdPlaceholder: 'User ID',
    passwordPlaceholder: 'Password',
    loginButton: 'Sign In to Dashboard',
    loginFailed: 'Unable to sign in right now.',
    forgotPassword: 'Forgot password?',
    createAccountPrompt: 'Don’t have an account?',
    createAccountAction: 'Create account',
    adminEmail: 'xpense.help@gmail.com',
    forgotPasswordSubject: 'Monetra password help request',
    forgotPasswordBody:
      'Hello Monetra admin,\n\nI need help resetting my Monetra password for user ID:\n\nThanks.',
    createAccountSubject: 'Monetra account creation request',
    createAccountBody:
      'Hello Monetra admin,\n\nI would like a Monetra account created for me. My details are:\n\nThanks.',
    emailFallbackMessage:
      'Unable to open your mail app. Please contact xpense.help@gmail.com directly.',
  },
  transactionsScreen: {
    title: 'Transactions',
    subtitle: 'All expenses and income in one place.',
    searchPlaceholder: 'Search by date, description, category, or type',
    monthSearchPlaceholder: 'Search this month',
    emptyTitle: 'No transactions yet',
    emptyMessage: 'Add your first expense or income to see it here.',
    emptySearchTitle: 'No matching transactions',
    emptySearchMessage: 'Try a different search term.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    uncategorized: 'Uncategorized',
    monthTotalLabel: 'Total spent',
    monthDetailBreakdown: 'Category Breakdown',
    monthDetailCategoryTransactions: 'Transactions',
    monthDetailRecent: 'Month Activity',
    editAction: 'Edit',
    deleteAction: 'Delete',
    deletingAction: 'Deleting...',
    deleteTitle: 'Delete transaction?',
    deleteMessage: 'This transaction will be removed permanently.',
    deleteCancel: 'Cancel',
    deleteConfirm: 'Delete',
    detailTitle: 'Transaction Details',
    detailAmountLabel: 'Amount',
    detailTypeLabel: 'Type',
    detailCategoryLabel: 'Category',
    detailDateLabel: 'Date',
    detailIdLabel: 'Transaction ID',
    backButton: 'Back',
  },
  dashboardScreen: {
    title: 'Dashboard',
    subtitle: 'Your money at a glance.',
    spendingTitle: 'This month spending',
    spendingTrend: 'Live from your expense activity',
    investmentTitle: 'This month investment',
    investmentAmount: '0',
    investmentTrend: 'Live from your investment activity',
    recentTitle: 'Latest Transactions',
    viewAll: 'View All',
    emptyRecent: 'No transactions yet.',
    insightTitle: 'Investment Insights',
    insightBadge: 'Investment Tracker',
    insightHeadline: 'Keep your portfolio entries up to date',
    insightBody:
      'Capture each investment move as it happens so your dashboard stays accurate month over month.',
    insightAction: 'Add Investment',
    noteTitle: 'Sync Health',
    noteBody:
      'Your dashboard is showing local-first data with Supabase sync in the background.',
    untitledTransaction: 'Untitled entry',
    todayUpper: 'TODAY',
    yesterdayUpper: 'YESTERDAY',
    daysAgoSuffix: 'DAYS AGO',
  },
  analysisScreen: {
    title: 'Monetra',
    month: 'Month',
    year: 'Year',
    totalSpent: 'Total Spent',
    vsLastMonth: 'vs last month',
    vsLastYear: 'vs last year',
    analysisTitle: 'Analysis',
    analysisSubtitle: 'Expense activity',
    categoriesTitle: 'Categories',
    viewAll: 'View All',
    allCategoriesTitle: 'All Categories',
    categoriesEmpty: 'No category data yet.',
    investmentsTitle: 'Investments',
    investmentsLocked: 'Live',
    investmentsLockedNote: 'Track investment entries from the Add Investment flow.',
    investmentGrowthTitle: 'PF Growth',
    investmentFundsTitle: 'Mutual Funds',
    chartPeakLabel: 'Peak',
    chartSelectedAmountLabel: 'Expense',
    chartSelectedDateLabel: 'Date',
    noDateSelected: 'Select a bar to inspect',
    noAnalyticsTitle: 'No analytics yet',
    noAnalyticsMessage: 'Add transactions to unlock monthly and yearly insights.',
    failedTitle: 'Unable to load analytics',
    failedMessage: 'Please try again in a moment.',
  },
  popup: {
    transactionAddedTitle: 'Transaction Added',
    transactionAddedMessage: 'Your transaction has been saved locally.',
    okButton: 'OK',
    databaseClearedTitle: 'Local Data Cleared',
    databaseClearedMessage: 'The local database has been reset.',
    transactionFailedTitle: 'Save Failed',
    transactionFailedMessage: 'Something went wrong while saving.',
    comingSoonTitle: 'Coming Soon',
    manageCategoriesMessage:
      'Category management will be available in a future update.',
    languageMessage: 'Language selection will be available in a future update.',
    exportDataMessage: 'Exporting data will be available in a future update.',
    importDataMessage: 'Importing data will be available in a future update.',
    backupSyncMessage: 'Backup and sync will be available in a future update.',
    quickDateMessage:
      'Quick date presets will be available in a future update.',
    recurringMessage:
      'Recurring transactions will be available in a future update.',
    multiCurrencyMessage:
      'Multi-currency support will be available in a future update.',
    investmentFlowMessage:
      'Investment and withdraw flows will be added later in the project.',
    investmentAddedTitle: 'Investment Added',
    investmentAddedMessage: 'Your investment has been saved locally.',
    investmentUpdatedTitle: 'Investment Updated',
    investmentUpdatedMessage: 'Your investment has been updated.',
    investmentFailedTitle: 'Unable to save investment',
    investmentFailedMessage: 'Please try again in a moment.',
    transactionUpdatedTitle: 'Transaction Updated',
    transactionUpdatedMessage: 'Your transaction has been updated.',
    transactionDeletedTitle: 'Transaction Deleted',
    transactionDeletedMessage: 'The transaction has been removed.',
  },
  investments: {
    title: 'Add Investment',
    newTitle: 'New Entry',
    editTitle: 'Edit Entry',
    listTitle: 'Investments',
    listThisMonth: 'This Month',
    listAll: 'All',
    listEmptyThisMonth: 'No investments added this month yet.',
    listEmptyAll: 'No investments added yet.',
    listPolicyNumber: 'Policy',
    listPolicyStart: 'Start',
    listNoNote: 'No note',
    amountLabel: 'Amount',
    amountPlaceholder: '0.00',
    typeLabel: 'Type',
    dateLabel: 'Date',
    policyNumberLabel: 'Policy Number',
    policyNumberPlaceholder: 'Enter policy number (if applicable)',
    policyStartDateLabel: 'Policy Start Date',
    policyHint:
      'Policy details auto-fill for repeat entries. Not applicable for stock market.',
    noteLabel: 'Note',
    notePlaceholder: 'Optional note (if applicable)',
    addButton: 'Add Investment',
    saveChangesButton: 'Save Changes',
    amountError: 'Enter a valid amount.',
    stockPolicyInfo: 'Policy fields are not required for stock market investments.',
    editAction: 'Edit',
    deleteAction: 'Delete',
    deleteTitle: 'Delete investment?',
    deleteMessage: 'This investment entry will be removed permanently.',
    deleteCancel: 'Cancel',
    deleteConfirm: 'Delete',
    detailTitle: 'Investment Details',
    detailAmountLabel: 'Amount',
    detailTypeLabel: 'Type',
    detailDateLabel: 'Date',
    detailIdLabel: 'Investment ID',
    modeAdd: 'Add',
    modeWithdraw: 'Withdraw',
    assetNameLabel: 'Asset Name',
    assetNamePlaceholder: 'e.g. S&P 500 Index Fund',
    amountCurrencyLabel: 'Amount (USD)',
    categoryDropdownLabel: 'Category',
    transactionDateDisplayLabel: 'Transaction Date',
    impactTitle: 'Portfolio Impact',
    impactSubtitle: 'Projected Growth Analysis',
    impactNewAllocationLabel: 'New Allocation',
    impactRiskAdjustedLabel: 'Risk Adjusted',
    impactNewAllocationValue: '24.5%',
    impactRiskAdjustedValue: '+1.2 pts',
    impactFootnote:
      'Adding this asset will diversify your exposure to the technology sector, reducing overall portfolio volatility by approximately 4%.',
    entryNoteAdd: 'Add entry',
    entryNoteWithdraw: 'Withdraw entry',
    typeNames: {
      mutual_fund: 'Mutual Fund',
      public_provident_fund: 'Public Provident Fund',
      stock_market: 'Stock Market',
      life_insurance: 'Life Insurance',
      fixed_deposit: 'Fixed Deposit',
    },
  },
  transactions: {
    title: 'Add Transaction',
    editTitle: 'Edit Transaction',
    expense: 'Expense',
    income: 'Income',
    expenseContext: 'Expense entry',
    incomeContext: 'Income entry',
    expenseContextHint: 'Quick add is set to expense by default.',
    incomeContextHint: 'Capture money received with the same flow.',
    amountLabel: 'Amount',
    amountPlaceholder: '0.00',
    descriptionLabel: 'Description',
    expensePlaceholder: 'What did you buy?',
    incomePlaceholder: 'Source of income',
    amountError: 'Enter a valid amount.',
    descriptionError: 'Description is required.',
    categoryError: 'Please select a category.',
    dateLabel: 'Date',
    categoryLabel: 'Category',
    allCategoriesTitle: 'Choose category',
    addCategoryTitle: 'Add category',
    categoryNameLabel: 'Category name',
    categoryNamePlaceholder: 'Enter category name',
    categoryEmojiLabel: 'Emoji',
    categoryEmojiPlaceholder: '✨',
    addCategoryButton: 'Add and use',
    moreCategories: 'More',
    addExpense: 'Add Expense',
    addIncome: 'Add Income',
    saveChanges: 'Save Changes',
    currencySymbol: '₹',
    dateIcon: '📅',
    closeIcon: '×',
    dateLocale: 'en-IN',
    quickActionTitle: 'Choose transaction type',
    quickActionExpense: 'Add expense',
    quickActionIncome: 'Add income',
    quickActionInvestment: 'Add investment',
    quickActionWithdraw: 'Withdraw',
    quickActionCancel: 'Cancel',
    quickActionSheetTitle: 'New Entry',
    quickActionSheetSubtitle:
      'Select the nature of your transaction to begin the vault update.',
    quickActionExpenseTitle: 'Track Expense',
    quickActionExpenseDescription:
      'Record daily spending, recurring bills, and lifestyle cash flow.',
    quickActionExpenseAction: 'Continue to Flow →',
    quickActionInvestmentTitle: 'Manage Investment',
    quickActionInvestmentDescription:
      'Update growth assets, portfolio additions, or process withdrawals.',
    quickActionInvestmentAction: 'Enter Growth Vault →',
    quickActionIncomeTitle: 'Track Income',
    quickActionIncomeDescription:
      'Log salary, dividends, freelance payments, and other inflows.',
    quickActionIncomeAction: 'Start Entry →',
    quickActionDismiss: '× Dismiss',
  },
  categories: {
    expense: {
      food: 'Food',
      transport: 'Transport',
      shopping: 'Shopping',
      entertainment: 'Entertainment',
      bills: 'Bills',
      health: 'Health',
      other: 'Other',
    },
    income: {
      salary: 'Salary',
      freelance: 'Freelance',
      other: 'Other',
    },
  },
};
