import { StyleSheet } from 'react-native';

import { spacing, typography, type ThemeColors } from '../../theme';

export const createStyles = (colors: ThemeColors) => {
  const isDarkTheme = colors.background === '#0B1220';

  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkTheme ? colors.background : '#FFFFFF',
  },
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.s14,
    paddingBottom: spacing.s32,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.s16,
    paddingBottom: spacing.s12,
    borderBottomWidth: isDarkTheme ? 0 : 1,
    borderBottomColor: isDarkTheme ? 'transparent' : '#E5E7EB',
  },
  backButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s12,
  },
  backButtonPressed: {
    opacity: 0.8,
  },
  backIcon: {
    fontSize: 24,
    lineHeight: 24,
    color: colors.textPrimary,
    marginTop: -2,
  },
  headerTitle: {
    fontSize: typography.size.base,
    fontWeight: typography.weight.bold,
    color: isDarkTheme ? colors.textPrimary : '#191C1E',
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: isDarkTheme ? colors.surfaceStrongAlt : '#F3F4F6',
    borderRadius: 14,
    padding: spacing.s4,
    marginBottom: spacing.s16,
  },
  segment: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: isDarkTheme ? colors.surfaceMuted : '#FFFFFF',
  },
  segmentDisabled: {
    opacity: 0.78,
  },
  segmentText: {
    fontSize: typography.size.sm,
    fontWeight: typography.weight.medium,
    color: isDarkTheme ? colors.muted : '#6B7280',
  },
  segmentTextActive: {
    color: isDarkTheme ? colors.successBright : '#10B981',
  },
  segmentTextDisabled: {
    color: isDarkTheme ? colors.tabInactive : '#9CA3AF',
  },
  addCategoryCard: {
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: isDarkTheme ? colors.success : '#ECFDF5',
    borderWidth: isDarkTheme ? 0 : 1,
    borderColor: isDarkTheme ? 'transparent' : '#BBEBDD',
    marginBottom: spacing.s24,
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s16,
  },
  addCategoryCardPressed: {
    opacity: 0.9,
  },
  addCategoryGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: colors.successBright,
    opacity: isDarkTheme ? 0.16 : 0,
    top: -132,
    left: -54,
  },
  addCategoryIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkTheme ? colors.successSoft : '#10B981',
    marginRight: spacing.s12,
  },
  addCategoryIcon: {
    fontSize: typography.size.xl,
    color: isDarkTheme ? colors.successBright : '#FFFFFF',
    marginTop: -2,
  },
  addCategoryContent: {
    flex: 1,
    paddingRight: spacing.s8,
  },
  addCategoryTitle: {
    fontSize: typography.size.lg,
    fontWeight: typography.weight.bold,
    color: isDarkTheme ? colors.primaryContrast : '#047857',
    marginBottom: spacing.s4,
  },
  addCategorySubtitle: {
    fontSize: typography.size.sm,
    color: isDarkTheme ? colors.primaryContrast : '#4B5563',
    opacity: isDarkTheme ? 0.82 : 1,
    lineHeight: 20,
  },
  addCategoryArrow: {
    fontSize: 30,
    color: isDarkTheme ? colors.primaryContrast : '#A7F3D0',
    opacity: 0.95,
    marginTop: -2,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s12,
  },
  formTitle: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
  },
  cancelEditText: {
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
    color: colors.success,
  },
  formTypeRow: {
    flexDirection: 'row',
    marginBottom: spacing.s12,
    gap: spacing.s8,
  },
  formTypeChip: {
    flex: 1,
    minHeight: 36,
    borderRadius: 12,
    backgroundColor: isDarkTheme ? colors.surfaceSecondary : '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formTypeChipActive: {
    backgroundColor: isDarkTheme ? colors.successMuted : '#FFFFFF',
  },
  formTypeChipDisabled: {
    opacity: 0.55,
  },
  formTypeChipText: {
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
    color: isDarkTheme ? colors.muted : '#8B9198',
  },
  formTypeChipTextActive: {
    color: isDarkTheme ? colors.success : '#0F8A62',
  },
  formTypeChipTextDisabled: {
    color: isDarkTheme ? colors.muted : '#9CA3AF',
  },
  inputContainer: {
    minHeight: 54,
    borderWidth: 0,
    borderRadius: 14,
    backgroundColor: colors.surfaceSecondary,
    paddingHorizontal: spacing.s16,
  },
  input: {
    fontSize: typography.size.md,
    color: colors.textPrimary,
  },
  formCard: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: spacing.s16,
  },
  formActions: {
    marginTop: spacing.s10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
  },
  saveButton: {
    flex: 1,
    minHeight: 64,
    borderRadius: 32,
  },
  listSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s12,
  },
  listSectionTitle: {
    fontSize: 12,
    fontWeight: typography.weight.bold,
    color: isDarkTheme ? colors.textPrimary : '#6B7280',
    letterSpacing: 1,
  },
  listSectionCount: {
    fontSize: 11,
    fontWeight: typography.weight.semiBold,
    color: isDarkTheme ? '#102517' : '#047857',
    backgroundColor: isDarkTheme ? colors.success : '#D1FAE5',
    borderRadius: 999,
    paddingHorizontal: spacing.s8,
    paddingVertical: 3,
  },
  loaderCard: {
    minHeight: 180,
    backgroundColor: colors.surface,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: spacing.s20,
  },
  emptyTitle: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.bold,
    color: colors.textPrimary,
    marginBottom: spacing.s8,
  },
  emptyMessage: {
    fontSize: typography.size.sm,
    color: colors.muted,
    lineHeight: 22,
  },
  categoryCard: {
    backgroundColor: isDarkTheme ? colors.surface : '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.s14,
    borderWidth: isDarkTheme ? 0 : 1,
    borderColor: isDarkTheme ? 'transparent' : '#E5E7EB',
  },
  categoryIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: isDarkTheme ? colors.surfaceSecondary : '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s14,
  },
  categoryEmoji: {
    fontSize: 22,
  },
  categoryMain: {
    flex: 1,
    paddingRight: spacing.s12,
  },
  categoryTitle: {
    fontSize: typography.size.md,
    fontWeight: typography.weight.semiBold,
    color: isDarkTheme ? colors.textPrimary : '#191C1E',
    marginBottom: spacing.s4,
  },
  categoryMeta: {
    fontSize: typography.size.sm,
    color: isDarkTheme ? colors.muted : '#4B5563',
  },
  categoryActions: {
    alignItems: 'flex-end',
    gap: spacing.s8,
  },
  editIconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  editIcon: {
    fontSize: 18,
    color: isDarkTheme ? colors.textSecondary : '#4B5563',
    marginTop: -1,
  },
  actionChip: {
    minWidth: 72,
    borderRadius: 14,
    backgroundColor: colors.accentBlueSoft,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s8,
    alignItems: 'center',
  },
  actionChipPressed: {
    opacity: 0.8,
  },
  actionChipText: {
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
    color: colors.textPrimary,
  },
  deleteChip: {
    minWidth: 82,
    borderRadius: 14,
    backgroundColor: colors.errorSoft,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s8,
    alignItems: 'center',
  },
  deleteChipText: {
    fontSize: typography.size.sm,
    fontWeight: typography.weight.semiBold,
    color: colors.error,
  },
  deleteBlockedText: {
    fontSize: typography.size.sm,
    color: isDarkTheme ? colors.muted : '#8B9198',
    flexShrink: 1,
    marginRight: spacing.s8,
  },
  composerScreen: {
    flex: 1,
    backgroundColor: isDarkTheme ? colors.background : '#F3F4F6',
  },
  composerContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.s32,
  },
  composerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.s18,
  },
  composerTitle: {
    fontSize: typography.size.lg,
    fontWeight: typography.weight.bold,
    color: isDarkTheme ? colors.successBright : '#2A2F36',
  },
  previewWrap: {
    alignItems: 'center',
    marginTop: spacing.s8,
    marginBottom: spacing.s20,
  },
  previewCircle: {
    width: 130,
    height: 130,
    borderRadius: 65,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkTheme ? colors.surfaceMuted : '#86EFAC',
    borderWidth: isDarkTheme ? 0 : 3,
    borderColor: isDarkTheme ? 'transparent' : '#FFFFFF',
  },
  previewEmoji: {
    fontSize: 52,
  },
  previewEditBadge: {
    position: 'absolute',
    right: '35%',
    top: 92,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: isDarkTheme ? colors.success : '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewEditIcon: {
    fontSize: 12,
    color: isDarkTheme ? colors.primaryContrast : '#0F8A62',
    marginTop: -1,
  },
  previewLabel: {
    marginTop: spacing.s10,
    fontSize: typography.size.sm,
    color: colors.muted,
    letterSpacing: 1,
  },
  sectionLabel: {
    fontSize: 11,
    color: isDarkTheme ? colors.textSecondary : '#6B7280',
    letterSpacing: 1,
    fontWeight: typography.weight.semiBold,
    marginBottom: spacing.s10,
  },
  composerInputContainer: {
    minHeight: 56,
    borderWidth: 0,
    borderRadius: 14,
    backgroundColor: isDarkTheme ? colors.surfaceStrongAlt : '#EDEFF2',
    paddingHorizontal: spacing.s16,
    marginBottom: spacing.s18,
  },
  iconHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.s8,
  },
  popularBadge: {
    borderRadius: 12,
    backgroundColor: isDarkTheme ? colors.successSoft : '#D1FAE5',
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.s4,
    marginBottom: spacing.s10,
  },
  popularBadgeText: {
    fontSize: typography.size.xs,
    color: isDarkTheme ? colors.successBright : '#0F8A62',
    fontWeight: typography.weight.bold,
  },
  iconGrid: {
    backgroundColor: isDarkTheme ? colors.surface : '#EDEFF2',
    borderRadius: 16,
    padding: spacing.s12,
    marginBottom: spacing.s18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.s8,
  },
  iconCell: {
    width: '15%',
    minWidth: 42,
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkTheme ? colors.surfaceSecondary : '#E3E6EA',
  },
  iconCellActive: {
    borderWidth: isDarkTheme ? 2 : 0,
    borderColor: colors.successBright,
    backgroundColor: isDarkTheme ? colors.surfaceSecondary : '#B7F0D4',
  },
  iconCellText: {
    fontSize: 22,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  });
};
